name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-magicjson:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
        test-lib: ["pytest", "smalltest"]
        include:
          - test-lib: "pytest"
            test-pip: "pytest"
          - test-lib: "smalltest"
            test-pip: "git+https://github.com/DavidCEllis/smalltest.git"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ${{ matrix.test-pip }}
        python -m pip install coverage
        python -m pip install -e .
    - name: Test with ${{ matrix.test-lib }}
      run: |
        ${{ matrix.test-lib }}
